### ISSUE TITLE
can you add  the anchor at the html page ?

### ISSUE THREAD

**Issue by joostshao** [aosabook/aosabook#11]
http://www.aosabook.org/en/posa/high-performance-networking-in-chrome.html

for example:
in the article  : 
High Performance Networking in Chrome

<a href="#top"> Chrome’s Network Stack from 10,000 Feet  </a>

**Comment by rgov** [comment]
Hi @joostshao, I'm not sure I understand your request. Do you want the section headings to have anchors attached?
