### ISSUE TITLE
Typo in Volume II, Chapter 1 ('Scalable Web...') (online) (probably also ebook and print)

### ISSUE THREAD

**Issue by amyrbrown** [aosabook/aosabook#24]
From a reader: 

Current:

>Imagine there is a request for the same data (let's call it littleB) 
across several nodes, and that piece of data is not in the cache. 
If that request is routed **thought** the proxy, then all of those requests 
can be collapsed into one...

Expected:

>Imagine there is a request for the same data (let's call it littleB)
across several nodes, and that piece of data is not in the cache.
If that request is routed **through** the proxy, then all of those requests
can be collapsed into one...

So "thought" should be "through" in "routed thought the proxy".

**Comment by merwok** [comment]
Where is the typo?  (assuming “type” in the title means “typo”)

**Comment by amyrbrown** [comment]
Sorry, I edited the comment to clarify -- it's in the last line.

And wow, I made a "typo" in "typo"! That's epic. 😬
